sipa,2020-11-18 02:28:48,Concept ACK,https://github.com/bitcoin/bitcoin/pull/20411#issuecomment-729335775,729335775,
MarcoFalke,2020-11-18 07:19:57,review ACK 0a7eedc35afd5c73d5ab7d2b5b305f8c795e5b42,https://github.com/bitcoin/bitcoin/pull/20411#issuecomment-729488002,729488002,
troygiorshev,2020-11-25 07:07:17,"`git range-diff master 0a7eedc 68500bb`\n\nTrivial rebase since 19509 needs a rebase and will be based off of this PR.",https://github.com/bitcoin/bitcoin/pull/20411#issuecomment-733512143,733512143,
DrahtBot,2020-11-29 02:54:37,"<!--e57a25ab6845829454e8d69fc972939a-->\n\nThe following sections might be updated with supplementary metadata relevant to reviewers and maintainers.\n\n<!--174a7506f384e20aa4161008e828411d-->\n### Conflicts\nReviewers, this pull request conflicts with the following ones:\n\n* #20277 (p2p: Stop processing unrequested transactions during IBD and extend p2p_ibd_txrelay.py coverage by ariard)\n* #201",https://github.com/bitcoin/bitcoin/pull/20411#issuecomment-735321241,735321241,
troygiorshev,2020-12-02 14:54:34,"Fixed the error handling here, sorta.  The error wouldn't be in the struct unpacking as suggested, it would be in the file reading.  (The try/catch is expecting the last byte to only optionally exist)  However, it's not clear to me that `f.read()` fails with the same error on all systems.  It's a `ValueError` in at least some systems, but I'm worried about breaking things, especially with this not",https://github.com/bitcoin/bitcoin/pull/20411#issuecomment-737280344,737280344,
troygiorshev,2020-12-02 14:57:17,"Rebased onto #20524.\n\nThis is ready for re-review.",https://github.com/bitcoin/bitcoin/pull/20411#issuecomment-737282291,737282291,
DrahtBot,2020-12-12 13:02:51,"<!--cf906140f33d8803c4a75a2196329ecb-->\nüêô This pull request conflicts with the target branch and [needs rebase](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#rebasing-changes).\n\n<sub>Want to unsubscribe from rebase notifications on this pull request? Just convert this pull request to a ""draft"".</sub>",https://github.com/bitcoin/bitcoin/pull/20411#issuecomment-743752991,743752991,
jnewbery,2021-01-25 09:32:27,"@troygiorshev are you planning to rebase this, or should we mark it as up for grabs?",https://github.com/bitcoin/bitcoin/pull/20411#issuecomment-766682195,766682195,
jnewbery,2021-02-20 10:11:33,Marking this as up for grabs,https://github.com/bitcoin/bitcoin/pull/20411#issuecomment-782600095,782600095,
jnewbery,2021-02-20 10:13:51,"The first 6 commits in this PR were merged in #20524, so it's only the final _Unconditionally check for fRelay field in test framework_ commit that would need to be included in a new PR.",https://github.com/bitcoin/bitcoin/pull/20411#issuecomment-782600365,782600365,
MarcoFalke,2020-11-18 06:18:27,"```suggestion\n```\n\nLooks like you still treat it as optional, no?\n\nEDIT: Oh, nvm. You want it this way.",https://github.com/bitcoin/bitcoin/pull/20411#discussion_r525838756,525838756,test/functional/test_framework/messages.py
laanwj,2020-11-22 10:54:57,"Please don't use a blanket except here, but catch the specific exception `struct.error`. This could potentially mask another error, even ""KeyboardInterrupt"" (ctrl-C).",https://github.com/bitcoin/bitcoin/pull/20411#discussion_r528317475,528317475,test/functional/test_framework/messages.py
MarcoFalke,2020-11-23 07:01:29,"On a second thought,  I don't think this generally works the way you want it to work. (See my latest comment on your other pull request: https://github.com/bitcoin/bitcoin/pull/19509#issuecomment-729462566 )\n\nSo I've unresolved this conversation again.",https://github.com/bitcoin/bitcoin/pull/20411#discussion_r528499393,528499393,test/functional/test_framework/messages.py
MarcoFalke,2020-11-23 07:01:46,Would probably be best to remove the `except` wholesale.  https://github.com/bitcoin/bitcoin/pull/20411/files#r528499393,https://github.com/bitcoin/bitcoin/pull/20411#discussion_r528499478,528499478,test/functional/test_framework/messages.py
jnewbery,2020-11-27 10:03:26,"This isn't new. It's simply moving the try-except out of an if block, but there's no harm in fixing it up in this PR.",https://github.com/bitcoin/bitcoin/pull/20411#discussion_r531499646,531499646,test/functional/test_framework/messages.py
