MarcoFalke,2020-01-28 15:14:46,"ACK 0dae5a5c34ef54ad912382836d12688813745bc5\n\nThanks for the fix",https://github.com/bitcoin/bitcoin/pull/18013#issuecomment-579293558,579293558,
instagibbs,2020-01-28 15:15:15,I wonder if there might be a good place to add a really basic CI test that makes sure bench jobs can run successfully? ,https://github.com/bitcoin/bitcoin/pull/18013#issuecomment-579293804,579293804,
MarcoFalke,2020-01-28 15:16:19,"@instagibbs There is, and all benches do run successfully. This fixes an issue where the `--filter=....` option no longer works correctly, which we don't check in CI",https://github.com/bitcoin/bitcoin/pull/18013#issuecomment-579294329,579294329,
instagibbs,2020-01-28 15:18:16,@MarcoFalke ok well that's a suggestion :) ,https://github.com/bitcoin/bitcoin/pull/18013#issuecomment-579295342,579295342,
MarcoFalke,2020-01-28 15:23:07,"Here is the existing check, which is run in ci: https://github.com/bitcoin/bitcoin/blob/94c6f2bba45100abeaf310057a989f8644115eaf/src/Makefile.test.include#L594",https://github.com/bitcoin/bitcoin/pull/18013#issuecomment-579297955,579297955,
DrahtBot,2020-01-28 16:58:22,"<!--e57a25ab6845829454e8d69fc972939a-->\n\nThe following sections might be updated with supplementary metadata relevant to reviewers and maintainers.\n\n<!--174a7506f384e20aa4161008e828411d-->\n### Conflicts\nReviewers, this pull request conflicts with the following ones:\n\n* [#18011](https://drahtbot.github.io/bitcoin_core_issue_redirect/r/18011.html) (Replace current benchmarking framework with",https://github.com/bitcoin/bitcoin/pull/18013#issuecomment-579350178,579350178,
emilengler,2020-01-28 17:24:37,"I get this error:\n```\n$ src/bench/bench_bitcoin -filter=*\nterminate called after throwing an instance of 'std::regex_error'\n  what():  regex_error\n```\nAm I doing something wrong",https://github.com/bitcoin/bitcoin/pull/18013#issuecomment-579362380,579362380,
elichai,2020-01-28 17:28:36,"> I get this error:\n> \n> ```\n> $ src/bench/bench_bitcoin -filter=*\n> terminate called after throwing an instance of 'std::regex_error'\n>   what():  regex_error\n> ```\n> \n> Am I doing something wrong\n\nthat seems to be unrelated to the bug I'm fixing, the regex engine here(`std::regex`) isn't great. \nTry something like `-filter=RIPEMD160|SHA256|SHA1`",https://github.com/bitcoin/bitcoin/pull/18013#issuecomment-579364188,579364188,
