jonasschnelli,2020-05-28 07:39:26,"Test seems to fail:\nhttps://bitcoinbuilds.org/index.php?job=b27a270b-c15a-4a48-bf46-26b3cc36a464\n",https://github.com/bitcoin/bitcoin/pull/19078#issuecomment-635170430,635170430,
DrahtBot,2020-06-02 02:43:35,<!--e57a25ab6845829454e8d69fc972939a-->\n\nThe following sections might be updated with supplementary metadata relevant to reviewers and maintainers.\n\n<!--174a7506f384e20aa4161008e828411d-->\n### Conflicts\nNo conflicts as of last run.,https://github.com/bitcoin/bitcoin/pull/19078#issuecomment-637235804,637235804,
jonatack,2020-06-05 18:05:47,"Concept ACK.\n\nSeeing this error: Assertion `new_tx' failed:\n```\n2020-06-05T18:01:34.518000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_hf5xwzyh\n2020-06-05T18:01:34.975000Z TestFramework (INFO): Testing that various invalid commands raise with specific error messages\n2020-06-05T18:01:35.809000Z TestFramework (INFO): Calling wallet tool info, testing output",https://github.com/bitcoin/bitcoin/pull/19078#issuecomment-639673738,639673738,
achow101,2020-08-25 17:29:48,"#19805 is a potential solution to the test failure as it just avoids deserializing those records entirely.\n\n#19793 is a another potential solution to the test failure where the assert is removed.",https://github.com/bitcoin/bitcoin/pull/19078#issuecomment-680166791,680166791,
ryanofsky,2020-08-25 18:56:41,"> #19805 is a potential solution to the test failure as it just avoids deserializing those records entirely.\n> \n> #19793 is a another potential solution to the test failure where the assert is removed.\n\nMaybe I should look at the test to understand better, but both of these changes are avoiding failures when there are duplicate transactions in the database. But we still don't know how dupl",https://github.com/bitcoin/bitcoin/pull/19078#issuecomment-680210564,680210564,
achow101,2020-08-25 19:03:37,"> But we still don't know how duplicate transactions are winding up in the database to begin with?\n\nThe duplicate transactions are showing up in the records the salvage pulls from the database. This doesn't mean the database actually contains duplicate transactions but is actually more of an artifact of the aggressive salvage.\n\nSpecifically, the aggressive salvage will likely recover delet",https://github.com/bitcoin/bitcoin/pull/19078#issuecomment-680214016,680214016,
MarcoFalke,2020-10-15 08:16:57,Rebased,https://github.com/bitcoin/bitcoin/pull/19078#issuecomment-708983312,708983312,
MarcoFalke,2020-11-03 18:40:25,Please don't merge this. The failure still happens intermittently.,https://github.com/bitcoin/bitcoin/pull/19078#issuecomment-721307686,721307686,
meshcollider,2021-09-28 09:33:30,"@MarcoFalke how often does the intermittent test failure occur? I've rebased this on [a branch](https://github.com/meshcollider/bitcoin/commits/202109_salvage) which incorporates a few other salvage things, which fixes the assert(new_tx) thing again. I haven't been able to hit #20151 yet after multiple re-runs locally.",https://github.com/bitcoin/bitcoin/pull/19078#issuecomment-929022312,929022312,
MarcoFalke,2021-09-28 10:12:07,"How often did you try? I am running \n\n```\nwhile test/functional/tool_wallet.py --legacy-wallet ; do ( echo 1 >> /tmp/runs )  ; done\n```\n\nand it fails after 36 tries:\n\n```\n$ wc -l  /tmp/runs \n36 /tmp/runs\n",https://github.com/bitcoin/bitcoin/pull/19078#issuecomment-929049998,929049998,
achow101,2020-07-22 16:36:11,I had to add `self.nodes[0].rescanblockchain(0)` to make this pass after merging with #19457,https://github.com/bitcoin/bitcoin/pull/19078#discussion_r458929932,458929932,test/functional/tool_wallet.py
ryanofsky,2020-10-21 23:46:27,"In commit ""test: Add salvage test for wallet tool"" (fa6154b3aa904eb39e6e537ff99106b6e022701b)\n\n\nIt seems the test is failing on this line due to stderr output https://travis-ci.org/github/bitcoin/bitcoin/jobs/735969416#L2582:\n\n```\nSalvage: WARNING: Number of keys in data does not match number of values.\nSalvage: WARNING: Unexpected end of file while reading salvage output.\nWARNING:",https://github.com/bitcoin/bitcoin/pull/19078#discussion_r509798005,509798005,test/functional/tool_wallet.py
MarcoFalke,2020-10-22 07:17:22,#20151 ,https://github.com/bitcoin/bitcoin/pull/19078#discussion_r509931859,509931859,test/functional/tool_wallet.py
