MarcoFalke,2016-10-05T07:43:52Z,utACK 6976db2\n,https://github.com/bitcoin/bitcoin/pull/8882#issuecomment-251604808,251604808,
sdaftuar,2016-10-06T13:20:05Z,I suspect the failure in sendheaders may have the same underlying cause:a generate() call where the block announcements might be arriving later than expected.  I'll try to fix that up in this PR as well.\n,https://github.com/bitcoin/bitcoin/pull/8882#issuecomment-251959119,251959119,
sdaftuar,2016-10-06T18:42:02Z,I believe I've addressed the occasional test failure in sendheaders.py as well now.\n,https://github.com/bitcoin/bitcoin/pull/8882#issuecomment-252052365,252052365,
MarcoFalke,2016-10-08T19:33:03Z,utACK b55d941\n,https://github.com/bitcoin/bitcoin/pull/8882#issuecomment-252443773,252443773,
instagibbs,2016-10-10T08:46:22Z,utACK b55d9411e7e1aa36ddabba3b942f2e1c736c1bd9\n,https://github.com/bitcoin/bitcoin/pull/8882#issuecomment-252563172,252563172,
btcdrak,2016-10-10T17:39:06Z,utACK d6c83b95cff2ff290533593719d6501ecf128f13\n,https://github.com/bitcoin/bitcoin/pull/8882#issuecomment-252688664,252688664,
