promag,2019-01-15T12:46:47Z,"> but that requires quite a few lines in Python\n\nI think it's preferable.",https://github.com/bitcoin/bitcoin/pull/15171#issuecomment-454380371,454380371,
laanwj,2019-01-15T14:06:42Z,"Retrying is definitely preferableâ€”fixed waits are a waste of valuable testing time when they're not necessary, and fragile otherwise.",https://github.com/bitcoin/bitcoin/pull/15171#issuecomment-454403504,454403504,
MarcoFalke,2019-01-15T16:43:35Z,Why is `shutdown` not blocking until the logs are flushed :(,https://github.com/bitcoin/bitcoin/pull/15171#issuecomment-454461861,454461861,
Empact,2019-01-16T02:06:49Z,"The `shutdown` is unrelated - `logging` deals with `/test_framework.log`. This is the debug log for `node0`, which is apparently still active despite this being the last log entries. Not sure where the access is coming from:\n\n```\n[00:27:35]  node0 2019-01-15T02:08:41.638177Z BerkeleyEnvironment::Flush: wallet.dat checkpoint \n[00:27:35]  node0 2019-01-15T02:08:41.644178Z BerkeleyEnvironment",https://github.com/bitcoin/bitcoin/pull/15171#issuecomment-454623881,454623881,
MarcoFalke,2019-01-17T16:07:19Z,"I mean `logging.shutdown` https://docs.python.org/3/library/logging.html#logging.shutdown\n\nThe doc doesn't really say if it is async or sync",https://github.com/bitcoin/bitcoin/pull/15171#issuecomment-455228386,455228386,
Empact,2019-01-17T21:33:28Z,"I think they're distinct concerns, because they concern different files/folders. Seems `logging` operates on`test_framework.log`, at least in this context, vs `node0/regtest/debug.log`.\n\nhttps://github.com/bitcoin/bitcoin/blob/cd42553b1178a48a16017eff0b70669c84c3895c/test/functional/test_framework/test_framework.py#L395-L398\n\nI'm not clear on is what would be accessing the log though. Shut",https://github.com/bitcoin/bitcoin/pull/15171#issuecomment-455339923,455339923,
Empact,2019-01-25T04:09:50Z,"I haven't seen this since, so we may want to hold on it until it shows up again.",https://github.com/bitcoin/bitcoin/pull/15171#issuecomment-457449182,457449182,
Empact,2019-01-30T23:20:43Z,Closing pending possible future sighting.,https://github.com/bitcoin/bitcoin/pull/15171#issuecomment-459150410,459150410,
MarcoFalke,2019-01-15T22:32:34Z,"I'd prefer to pass in the exception here over a wildcard . Or, since this is only used once, could just make the function `def` inline in test_framework.py",https://github.com/bitcoin/bitcoin/pull/15171#discussion_r248088805,248088805,test/functional/test_framework/util.py
