luke-jr,2014-09-14T05:30:04Z,I tested this on testnet3; txid aca2f7d70e26bd2d902d50ec80a2bb6cd64d36894e8f3fa1eebcc1620b8c722b\n,https://github.com/bitcoin/bitcoin/pull/4909#issuecomment-55516131,55516131,
jgarzik,2014-09-14T05:47:09Z,"Fix is correct.  Can you please add a test that fails in master, and works with your fix?\n\nThe execution command line goes into src/test/data/bitcoin-util-test.json, and typically you either (a) prepare a canned output for comparison, or (b) indicate bitcoin-tx returns a failure error code.\n",https://github.com/bitcoin/bitcoin/pull/4909#issuecomment-55516386,55516386,
luke-jr,2014-09-14T06:06:01Z,done\n,https://github.com/bitcoin/bitcoin/pull/4909#issuecomment-55516661,55516661,
jgarzik,2014-09-14T06:26:42Z,"```\nTraceback (most recent call last):\n  File ""./test/bitcoin-util-test.py"", line 11, in <module>\n    ""bitcoin-util-test.json"")\n  File ""/mnt/bitcoin/linux-build/src/test/bctest.py"", line 50, in bctester\n    bctest(testDir, testObj)\n  File ""/mnt/bitcoin/linux-build/src/test/bctest.py"", line 24, in bctest\n    outputData = open(testDir + ""/"" + outputFn).read()\nIOError: [Errno 2] No such file ",https://github.com/bitcoin/bitcoin/pull/4909#issuecomment-55516959,55516959,
jgarzik,2014-09-14T06:28:24Z,ut ACK once pull tester happy\n,https://github.com/bitcoin/bitcoin/pull/4909#issuecomment-55516987,55516987,
BitcoinPullTester,2014-09-14T06:43:57Z,"Automatic sanity-testing: PASSED, see http://jenkins.bluematt.me/pull-tester/p4909_a65e320747133723f02c1947a4cc257214325b0b/ for binaries and test log.\nThis test script verifies pulls every time they are updated. It, however, dies sometimes and fails to test properly.  If you are waiting on a test, please check timestamps to verify that the test.log is moving at http://jenkins.bluematt.me/pull-te",https://github.com/bitcoin/bitcoin/pull/4909#issuecomment-55517234,55517234,
sipa,2014-09-14T15:33:56Z,ut ACK\n,https://github.com/bitcoin/bitcoin/pull/4909#issuecomment-55529237,55529237,
