ryanofsky,2017-10-11T11:42:56Z,"This seems like a good change, but why are you calling it a bugfix? Can you add a description of the bug?",https://github.com/bitcoin/bitcoin/pull/11483#issuecomment-335782880,335782880,
pedrobranco,2017-10-11T13:10:46Z,"> This seems like a good change, but why are you calling it a bugfix? Can you add a description of the bug?\n\nIt's a bug because we should receive an array of JSON responses. \nIn this situation we are receiving an array with a boolean:\n```sh\n❯ bitcoin-cli -regtest importmulti '[{ ""keys"": [""cNcMUunXhVK1dXJ5riixtpYSxPXZnUAMGS4vpzwChdKmYY3Rz99v""], ""scriptPubKey"": { ""address"": ""n4YZAf4WE2XF3t",https://github.com/bitcoin/bitcoin/pull/11483#issuecomment-335804284,335804284,
pedrobranco,2017-10-17T15:03:53Z,Any thoughts when this can be merged?,https://github.com/bitcoin/bitcoin/pull/11483#issuecomment-337261893,337261893,
ryanofsky,2017-10-17T15:27:33Z,Looks ready to me. Mentioning @laanwj to maybe include in the next batch of merges.,https://github.com/bitcoin/bitcoin/pull/11483#issuecomment-337269870,337269870,
jonasschnelli,2017-10-17T16:14:00Z,"utACK a44a215177ab55b4a3b36a7980c313e908e2dd18\nAdded ""Needs back port"" tag.",https://github.com/bitcoin/bitcoin/pull/11483#issuecomment-337283888,337283888,
TheBlueMatt,2017-10-17T17:27:39Z,utACK a44a215177ab55b4a3b36a7980c313e908e2dd18,https://github.com/bitcoin/bitcoin/pull/11483#issuecomment-337305813,337305813,
MarcoFalke,2017-10-17T19:46:34Z,utACK a44a215\n\n(Backport label can be removed)\n,https://github.com/bitcoin/bitcoin/pull/11483#issuecomment-337348604,337348604,
promag,2017-10-17T21:31:10Z,utACK a44a215.,https://github.com/bitcoin/bitcoin/pull/11483#issuecomment-337378044,337378044,
promag,2017-10-11T10:56:51Z,Should be `true`?,https://github.com/bitcoin/bitcoin/pull/11483#discussion_r143976327,143976327,src/wallet/rpcdump.cpp
pedrobranco,2017-10-11T11:24:46Z,"Since when `success` is `false` returns the associated `error`, in this situation since there's no associated error, `success` should be true. Just like calling n times the `importprivkey` RPC for a given private key: it does not throw any error.",https://github.com/bitcoin/bitcoin/pull/11483#discussion_r143981335,143981335,src/wallet/rpcdump.cpp
promag,2017-10-11T11:39:02Z,"Right, but maybe that behaviour is wrong? Search for `throw JSONRPCError(RPC_WALLET_ERROR, ""The wallet already contains the private key for this address or script"");`",https://github.com/bitcoin/bitcoin/pull/11483#discussion_r143983935,143983935,src/wallet/rpcdump.cpp
promag,2017-10-11T11:41:08Z,"BTW, all previous exit points are exceptions, this is the only early return.",https://github.com/bitcoin/bitcoin/pull/11483#discussion_r143984293,143984293,src/wallet/rpcdump.cpp
pedrobranco,2017-10-11T13:08:05Z,"> Right, but maybe that behaviour is wrong? Search for throw JSONRPCError(RPC_WALLET_ERROR, ""The wallet already contains the private key for this address or script"");\n\nRight, so we can keep it consistent with the rest of the `importmulti` logic by throwing that error.",https://github.com/bitcoin/bitcoin/pull/11483#discussion_r144004598,144004598,src/wallet/rpcdump.cpp
ryanofsky,2017-10-11T15:17:23Z,"The test below (""Should not import an address with private key if is already imported"") seems good, but this test (""Should not import an already imported address"") is confusing to me.\n\nFor one thing, it doesn't seem to have anything to do with the bug, because it passes both before and after the bugfix. But also the description seems misleading because it is checking that success is true while",https://github.com/bitcoin/bitcoin/pull/11483#discussion_r144044790,144044790,test/functional/importmulti.py
pedrobranco,2017-10-11T16:10:51Z,I'm dropping this test.,https://github.com/bitcoin/bitcoin/pull/11483#discussion_r144059981,144059981,test/functional/importmulti.py
