vasild,2020-09-29 10:16:28,cc @hebasto,https://github.com/bitcoin/bitcoin/pull/20033#issuecomment-700608659,700608659,
hebasto,2020-09-29 10:21:49,"Concept ACK, obviously :) Thanks @vasild  !\n\nMind also integrating https://github.com/bitcoin/bitcoin/pull/19845#discussion_r495730125 as that change was unneeded?",https://github.com/bitcoin/bitcoin/pull/20033#issuecomment-700611242,700611242,
vasild,2020-09-29 10:37:49,"Well, I left it as is because\n\n```cpp\ntemplate <typename E>\nbool operator()(const E& e) const {\n```\n\nis more generic than\n\n```cpp\nbool operator()(const std::runtime_error& e) const {\n```\n\nboth work now but the former would also work if the exception does not inherit `std::runtime_error`.",https://github.com/bitcoin/bitcoin/pull/20033#issuecomment-700618520,700618520,
hebasto,2020-09-29 10:58:22,"I don't think the template function is required to make exception handling more generic for the following reasons:\n- all custom types in the project inherit from `std::runtime_error`\n- if this seems insufficient, the base `std::exception` type could be used",https://github.com/bitcoin/bitcoin/pull/20033#issuecomment-700627730,700627730,
ajtowns,2020-10-06 20:57:52,Please describe the actual changes in the pr title/description?,https://github.com/bitcoin/bitcoin/pull/20033#issuecomment-704548700,704548700,
fanquake,2020-10-31 12:31:22,"@vasild could you follow up here with @hebasto and @ajtowns comments, as this is a fairly straight-forward change.",https://github.com/bitcoin/bitcoin/pull/20033#issuecomment-719927547,719927547,
vasild,2020-10-31 14:09:15,Done!,https://github.com/bitcoin/bitcoin/pull/20033#issuecomment-719939173,719939173,
vasild,2020-10-31 15:58:35,"`./test/util/setup_common.h:166:10: note:   no known conversion for argument 1 from ‘const std::ios_base::failure’ to ‘const std::runtime_error&’` :bomb: \n\nhttps://travis-ci.org/github/bitcoin/bitcoin/jobs/740417628#L2831",https://github.com/bitcoin/bitcoin/pull/20033#issuecomment-719952830,719952830,
jonatack,2020-10-31 16:18:09,Interesting. I compiled and ran the unit tests without warnings.,https://github.com/bitcoin/bitcoin/pull/20033#issuecomment-719955152,719955152,
jonatack,2020-10-31 17:04:42,"re-ACK 89836a8 change since previous review is replacing std::runtime_error with std::exception, built/ran unit tests with gcc debian 10.2.0-15, then broke a few v3 net_tests involving `BOOST_CHECK_EXCEPTION`, rebuilt, ran `src/test/test_bitcoin -t net_tests -l all` and checked the error reporting.\n\nChange per `git diff b763174 89836a8` since previous review:\n```diff\ndiff --git a/src/test/",https://github.com/bitcoin/bitcoin/pull/20033#issuecomment-719960801,719960801,
hebasto,2020-10-31 22:59:49,"re-ACK 89836a82eec63f93bbe6c3bd6a52be26e71ab54d\n\n> `./test/util/setup_common.h:166:10: note: no known conversion for argument 1 from ‘const std::ios_base::failure’ to ‘const std::runtime_error&’` bomb\n> \n> https://travis-ci.org/github/bitcoin/bitcoin/jobs/740417628#L2831\n\nCentOS build uses pretty old gcc. Nice that CI caught that issue.\n\n",https://github.com/bitcoin/bitcoin/pull/20033#issuecomment-719999171,719999171,
